title: SE Research Patterns
description: "Patterns of good and bad research papers in Software Engineering. http://tiny.cc/sepat"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
