title: SE Research Patterns
description: "Patterns of good and bad research papers in Software Engineering.  <a href=\"http://tiny.cc/sepat\">http://tiny.cc/sep</a>"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
