title: SE Research Patterns
description: "How to assemble 'good' SE papers.  <a href=\"http://tiny.cc/sepat\">http://tiny.cc/sepat</a>"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
